# Generated by Django 3.2 on 2022-12-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativos',
            name='cotacao',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
