# Generated by Django 3.2 on 2022-12-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfaapp', '0003_alter_ativos_cotacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='nome',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
