# Generated by Django 3.2 on 2022-12-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfaapp', '0004_alter_ativos_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativos',
            name='switch_off_thread',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
