# Generated by Django 3.2 on 2022-12-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfaapp', '0005_ativos_switch_off_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos',
            name='switch_off_thread',
            field=models.BooleanField(null=True),
        ),
    ]
