# Generated by Django 3.2 on 2022-12-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfaapp', '0006_alter_ativos_switch_off_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativos',
            name='email_compra',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='ativos',
            name='email_venda',
            field=models.BooleanField(null=True),
        ),
    ]
